name: mt3-pytorch-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - protobuf==3.20.3
  - pip:
      - transformers
      - torch
      - librosa
      - ddsp
      - t5
      - note-seq
      - pretty-midi
      - einops
      - tensorflow==2.19.0
